<LoginScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(20)
        spacing: dp(10)
        MDLabel:
            text: "Введите логин и пароль от Rulate"
            halign: 'center'
        MDTextField:
            id: login_field
            hint_text: "Логин"
        MDTextField:
            id: pass_field
            hint_text: "Пароль"
            password: True
        MDRaisedButton:
            text: "Сохранить"
            on_release: root.do_login()