<LoadScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(10)
        MDProgressBar:
            id: progress_bar
            max: 100
            value: 0
        ScrollView:
            TextInput:
                id: log_output
                readonly: True
                background_color: 0,0,0,0
        MDRaisedButton:
            text: "На главный экран"
            on_release: app.sm.current = 'main_menu'